version: '2'
services:
  angular:
    build: .
    image: johnpapa/angular-cli
    command: ng serve --host 0.0.0.0
    volumes:
      - ./src/angular:/usr/app/angular
    working_dir: /usr/app/angular
    ports:
      - "4200:4200"
  express:
    build: .
    image: johnpapa/angular-cli
    command: node app.js
    volumes:
      - ./src/express:/usr/app/express
    working_dir: /usr/app/express
    ports:
      - "3000:3000"
